include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"
    - "**_options.dart"

linter:
  rules:
    directives_ordering: false
    sort_pub_dependencies: false
